"""expand_insert_card_functionality

Revision ID: 59dc7d7dff66
Revises: 32614886fe06
Create Date: 2026-01-01 20:44:25.060880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59dc7d7dff66'
down_revision: Union[str, Sequence[str], None] = '32614886fe06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skryfall_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scryfall_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mana_cost', sa.Float(), nullable=False),
    sa.Column('type_line', sa.String(), nullable=False),
    sa.Column('oracle_text', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scryfall_id')
    )
    op.create_table('collection_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scryfall_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scryfall_id'], ['skryfall_cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('card_pkey'))
    )
    op.drop_table('collection_cards')
    op.drop_table('skryfall_cards')
    # ### end Alembic commands ###
